### ISSUE TITLE
iOS package

### ISSUE THREAD

**Issue by profelis** [alebianco/ANE-Google-Analytics#6]
Problem only then package ipa for simulator.

Mac OS 10.7.4
XCode 4.5
Air sdk 3.4

<application xmlns="http://ns.adobe.com/air/application/3.4">

development branch
iPhoneSimulator5.0 or iPhoneSimulator5.1
package for simulator - error

```
ld: warning: -macosx_version_min not specificed, assuming 10.6
ld: warning: could not create compact unwind for __Unwind_Resume: non-standard register 0 being saved in prolog
ld: warning: could not create compact unwind for __Unwind_ForcedUnwind: non-standard register 0 being saved in prolog
ld: warning: could not create compact unwind for __Unwind_RaiseException: non-standard register 0 being saved in prolog
ld: warning: could not create compact unwind for __Unwind_Resume_or_Rethrow: non-standard register 0 being saved in prolog
```

ipa package - all ok

 iPhoneSimulator6.0
 package for simulator

```
[Fatal Error] :1:1: Content is not allowed in prolog.
java.io.IOException: PLIST generation failed due to SAX error:org.xml.sax.SAXParseException: Content is not allowed in prolog.
    at com.adobe.air.Plist.newFromString(Plist.java:351)
    at com.adobe.air.Plist.newFromFile(Plist.java:325)
    at com.adobe.air.ipa.IPAOutputStream.setSDKVersion(IPAOutputStream.java:1067)
    at com.adobe.air.ipa.IPAOutputStream.setPlatformSDKLocation(IPAOutputStream.java:969)
    at com.adobe.air.ipa.IPAPackager.setDeviceSDKDirectory(IPAPackager.java:187)
    at com.adobe.air.ADT.parseInput(ADT.java:920)
    at com.adobe.air.ADT.parsePackage(ADT.java:672)
    at com.adobe.air.ADT.parseArgsAndGo(ADT.java:570)
    at com.adobe.air.ADT.run(ADT.java:419)
    at com.adobe.air.ADT.main(ADT.java:469)
ld: warning: -macosx_version_min not specificed, assuming 10.6
ld: warning: could not create compact unwind for __Unwind_Resume: non-standard register 0 being saved in prolog
ld: warning: could not create compact unwind for __Unwind_ForcedUnwind: non-standard register 0 being saved in prolog
ld: warning: could not create compact unwind for __Unwind_RaiseException: non-standard register 0 being saved in prolog
ld: warning: could not create compact unwind for __Unwind_Resume_or_Rethrow: non-standard register 0 being saved in prolog
```

ipa package - all ok

**Comment by alebianco** [comment]
on the 5.0/5.1 simulator, those are just warnings, nothing to worry about. the app should get packaged correctly and run on the simulator.
i'm testing it with the demo project launched from the ant target that comes in the ant build file, seems to work ok here

on the 6.0 simulator, i can't test directly (can't upgrade xcode or i'll loose support to armv6 devices) but i've found that that's a know issue and adobe is working to get it fixed
source: http://forums.adobe.com/message/4724193

**Comment by profelis** [comment]
Thanks for answer.

I build in IDEA and it stop build after warnings.
